# Generated by Django 4.0.6 on 2022-08-03 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='loctioan',
            new_name='location',
        ),
    ]
